### ISSUE TITLE
how can i use this module in other file and class 

### ISSUE THREAD

**Issue by dev0zero** [kareman/FileSmith#14]
for example i have main.swift and Files.swift and i want use in Files class your module is this possible ?

my Code is 
`
import FileSmith
import Foundation

class Files: FileSmith {

  DirectoryPath.current = "/tmp"

  func writeDataToFile(data: String) {

  }
}
`

**Comment by kareman** [comment]
Hi, if you want to create a file and write some text to it you can do like this:

```swift
import FileSmith

DirectoryPath.current = "/tmp"
let file = try WritableFile(create: "filename.txt", ifExists: .open)
file.write("Whatever text you want to write to the file.")
```

You can use this code on its own in main.swift, or you can put it in a function in any file. But you cannot inherit from FileSmith with `class Files: FileSmith` because FileSmith is a module, not a class, and can only be imported.

**Comment by dev0zero** [comment]
thanx for reply, you are have good module.

**Comment by kareman** [comment]
You're welcome, glad you found it useful. 

I'll close this issue now as it seems the problem has been resolved.
